/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/antique_desk.glb -o components/3d/Desk.tsx --types 
Author: Matthew Collings (https://sketchfab.com/mtcollings)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/antique-desk-c491f647da5947978ba8113951ee2efc
Title: Antique Desk
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
type GLTFAction = THREE.AnimationAction;
type GLTFResult = GLTF & {
  nodes: {
    Handle_3_low_Desk_0: THREE.Mesh;
    Handle_2_low_Desk_0: THREE.Mesh;
    Draw_2_low_Desk_0: THREE.Mesh;
    Handle_4_low_Desk_0: THREE.Mesh;
    Draw_3_low_Desk_0: THREE.Mesh;
    Handle_1_low_Desk_0: THREE.Mesh;
    Draw_1_low_Desk_0: THREE.Mesh;
    Handle_6_low_Desk_0: THREE.Mesh;
    Handle_5_low_Desk_0: THREE.Mesh;
    Handle_8_low_Desk_0: THREE.Mesh;
    Handle_7_low_Desk_0: THREE.Mesh;
    Handle_10_low_Desk_0: THREE.Mesh;
    Handle_9_low_Desk_0: THREE.Mesh;
    Desk_low_Desk_0: THREE.Mesh;
  };
  materials: {
    Desk: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/antique_desk.glb",
  ) as unknown as GLTFResult; // <--- Acá está el truco: doble casteo
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.111}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Desk_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Draw_2_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Handle_3_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Handle_2_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Draw_3_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Handle_4_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Draw_1_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Handle_1_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Handle_6_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Handle_5_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Handle_8_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Handle_7_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Handle_10_low_Desk_0.geometry}
              material={materials.Desk}
            />
            <mesh
              geometry={nodes.Handle_9_low_Desk_0.geometry}
              material={materials.Desk}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/antique_desk.glb");
